services:
  usersvc:
    container_name: user-service
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8000
    networks:
      - usersvc-network

  mongodb:
    image: mongo
    container_name: user-service-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=abc123
      - MONGO_INITDB_DATABASE=userservice
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - usersvc-network

  mongo-express:
    container_name: user-service-mongo-express
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://admin:abc123@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
    ports:
      - 8081:8081
    networks:
      - usersvc-network
  
  redis:
    container_name: user-service-redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - usersvc-network

networks:
  usersvc-network: